import type { NextPage } from 'next';
import type { ReactNode } from 'react';
import Head from 'next/head';

import { Intro } from '../components/Intro';

import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>jvopinho</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<main>
				<Intro />
			</main>
		</div>
	);
};

export default Home;
