import type { NextPage } from 'next';
import type { PropsWithChildren, HTMLAttributes, DetailedHTMLProps } from 'react';
import Head from 'next/head';
import ReactMarkdown from 'react-markdown';
import RemarkGFM from 'remark-gfm';
import styled from 'styled-components';

import { Intro } from '../components/Intro';
import { Header } from '../components/Header';
import { Timeline, TimelineEvent } from '../components/Timeline';
import { Skills } from '../components/Skills';

import styles from '../styles/Home.module.scss';
import { timeline } from '../config';

const Section: React.FC<PropsWithChildren<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>>> = props => <section {...props} className={`${styles.section} ${props?.className || ''}`.trim()} />;

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>jvopinho</title>
				<meta name="description" content="Generated by create next app" />
				{/* <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<main>
				<Section style={{display: 'block'}} id={'intro'}>
					<Header />
					<Intro />
				</Section>

				<Section id={'skills'}>
					<h2><strong>#</strong> Skills</h2>
					<Skills />
				</Section>

				<Section id={'timeline'}>
					<h2><strong>#</strong> Timeline</h2>
					<Timeline>
						{timeline.map((line, index) => (
							<TimelineEvent title={line.title} key={`line-${index}`}>
								<ReactMarkdown remarkPlugins={[RemarkGFM]}>
									{line.content}
								</ReactMarkdown>
							</TimelineEvent>
						))}
					</Timeline>
				</Section>
			</main>
		</div>
	);
};

export default Home;
